name: Install Gobuster

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Gobuster
        run: go install github.com/OJ/gobuster/v3@latest

      - name: Verify Gobuster installation
        run: |
          git clone https://github.com/PortSwigger/param-miner.git
          curl -s https://wordlists-cdn.assetnote.io/data/manual/wordlist_with_underscores.txt > wlist2.txt
          gobuster fuzz -u "https://pmg-acg-users.verisign.com/FUZZ" -w wlist2.txt -b 404,400 --useragent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" -o output.txt -o output.txt -k -z
          cat output.txt
#        -t 1 --delay 105ms
